Fix build for clang-r563880
system/media/audio_utils/tests/run_remote_tests.cpp:48:27: error: too few arguments provided to function-like macro invocation
   48 |     remoteWorker->putc('c');
      |                           ^
prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/sysroot/usr/include/stdio.h:585:9: note: macro 'putc' defined here
  585 | #define putc(_ch, _fp) _IO_putc (_ch, _fp)
      |         ^

Change to a different name to avoid conflict.

Test: presubmit
Bug: 401330760
Change-Id: Ie3366de9516ab61705156bbc54e1064bf99ca4ff